# Generated by Django 5.0.3 on 2026-06-05 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(blank=True, max_length=100)),
                (
                    "segment",
                    models.CharField(db_index=True, default="Standard", max_length=50),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "customers",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["segment"], name="customers_segment_d7b3e3_idx"
                    ),
                    models.Index(
                        fields=["country", "city"], name="customers_country_c4bc48_idx"
                    ),
                ],
            },
        ),
    ]
