# Generated by Django 5.0.3 on 2026-06-05 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                ("sales_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("profit", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "discount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("region", models.CharField(db_index=True, max_length=100)),
                ("order_date", models.DateTimeField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales",
                        to="customers.customer",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "db_table": "sales",
                "ordering": ["-order_date"],
                "indexes": [
                    models.Index(
                        fields=["region", "order_date"], name="sales_region_2e0330_idx"
                    ),
                    models.Index(
                        fields=["order_date"], name="sales_order_d_75eced_idx"
                    ),
                ],
            },
        ),
    ]
