name = "sales-analytics-api"
main = "src/index.js"
compatibility_date = "2026-07-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "sales-db"
database_id = "9a8d557a-659f-4f0b-88cf-8486072304d2"
migrations_dir = "migrations"
