# Generated by Django 5.2.15 on 2026-06-25 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='supabase_uid',
            field=models.UUIDField(blank=True, help_text='Supabase Auth user UUID for linking with Supabase accounts', null=True, unique=True),
        ),
    ]
